version: '3.6'

services:
  mysql-m:
    image: mysql:5.7
    ports:
      - "33061:3306"
    env_file: configuration.env
    volumes:
      - ./mysql/master-my.cnf:/etc/mysql/conf.d/master.cnf
      - mysql_data_1:/var/lib/mysql

  mysql-s1:
    image: mysql:5.7
    ports:
      - "33062:3306"
    env_file: configuration.env
    volumes:
      - ./mysql/slave-1-my.cnf:/etc/mysql/conf.d/slave.cnf
      - mysql_data_2:/var/lib/mysql

  mysql-s2:
    image: mysql:5.7
    ports:
      - "33063:3306"
    env_file: configuration.env
    volumes:
      - ./mysql/slave-2-my.cnf:/etc/mysql/conf.d/slave.cnf
      - mysql_data_3:/var/lib/mysql

networks:
  application:
    driver: bridge

volumes:
  mysql_data_1: {}
  mysql_data_2: {}
  mysql_data_3: {}